# Site settings
author: Aaron Berns
title: Recent Projects
header-img: img/home-bg.png
email: anberns@gmail.com
copyright_name: Aaron Berns
description: > # this means to ignore newlines until "baseurl:"
  It's Me's Work!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  anberns

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
